module.exports = [
  {
    neckline: "ship",
    court: "princess",
    long: "long",
    color: "white",
    size: "34",
    designer: "vera wang",
    seller: "615a5a1ab5dd1839ac9cc34b",
    name: "elegant lace Gown",
    description: "a beautiful lace gown with a long train.",
    price: 2000,
    location: "new York",
    image: "../images/brittney-weng.jpg",
    sold: false
  },
  {
    neckline: "v-shaped",
    court: "straight",
    long: "long",
    color: "ivory",
    size: "36",
    designer: "monique lhuillier",
    seller: "615a5a1ab5dd1839ac9cc34b",
    name: "chantilly lace Gown",
    description: "a beautiful chantilly lace gown with an illusion back.",
    price: 3000,
    location: "los angeles",
    image: "../images/jonathan-borba.jpg",
    sold: false
  },
  {
    neckline: "square",
    court: "siren",
    long: "long",
    color: "ivory",
    size: "38",
    designer: "carolina herrera",
    seller: "615a5a1ab5dd1839ac9cc34b",
    name: "silk satin Gown",
    description: "a stunning silk satin gown with a sweetheart neckline.",
    price: 4000,
    location: "new York",
    image: "../images/jonathan-borba-B.jpg",
    sold: false
  },
  {
    neckline: "strapless",
    court: "empire",
    long: "long",
    color: "white",
    size: "40",
    designer: "oscar de la renta",
    seller: "615a5a1ab5dd1839ac9cc34b",
    name: "tulle Ball Gown",
    description: "a dreamy tulle ball gown with a sweetheart neckline.",
    price: 5000,
    location: "los angeles",
    image: "../images/scott-webb-.jpg",
    sold: false
  },
  {
    neckline: "halter",
    court: "straight",
    long: "long",
    color: "ivory",
    size: "42",
    designer: "marchesa",
    seller: "615a5a1ab5dd1839ac9cc34b",
    name: "embroidered tulle Gown",
    description: "an embroidered tulle gown with a halter neckline.",
    price: 6000,
    location: "new York",
    image: "../images/engin-akyurt.jpg",
    sold: false
  },
  {
    neckline: "round",
    court: "princess",
    long: "long",
    color: "white",
    size: "44",
    designer: "vera wang",
    seller: "615a5a1ab5dd1839ac9cc34b",
    name: "organza Gown",
    description: "a beautiful organza gown with a full skirt.",
    price: 7000,
    location: "los angeles",
    image: "../images/engin-akyurt.jpg",
    sold: false
  },
  {
    neckline: "heart",
    court: "siren",
    long: "long",
    color: "ivory",
    size: "46",
    designer: "monique lhuillier",
    seller: "615a5a1ab5dd1839ac9cc34b",
    name: "lace mermaid Gown",
    description: "a stunning lace mermaid gown with a sweetheart neckline.",
    price: 8000,
    location: "new York",
    image: "../images/scott-webb-.jpg",
    sold: false
  },
] 
