module.exports = [
  {
    neckline: "Ship",
    court: "Princess",
    long: "Long",
    color: "White",
    size: "34",
    designer: "Vera Wang",
    name: "Elegant Lace Gown",
    description: "A beautiful lace gown with a long train.",
    price: 2000,
    location: "New York",
    image: "../images/brittney-weng.jpg",
    sold: false
  },
  {
    neckline: "V-shaped",
    court: "Straight",
    long: "Long",
    color: "Ivory",
    size: "36",
    designer: "Monique Lhuillier",
    name: "Chantilly Lace Gown",
    description: "A beautiful Chantilly lace gown with an illusion back.",
    price: 3000,
    location: "Los Angeles",
    image: "../images/jonathan-borba.jpg",
    sold: false
  },
  {
    neckline: "Square",
    court: "Siren",
    long: "Long",
    color: "Ivory",
    size: "38",
    designer: "Carolina Herrera",
    name: "Silk Satin Gown",
    description: "A stunning silk satin gown with a sweetheart neckline.",
    price: 4000,
    location: "New York",
    image: "../images/jonathan-borba-B.jpg",
    sold: false
  },
  {
    neckline: "Strapless",
    court: "Empire",
    long: "Long",
    color: "White",
    size: "40",
    designer: "Oscar de la Renta",
    name: "Tulle Ball Gown",
    description: "A dreamy tulle ball gown with a sweetheart neckline.",
    price: 5000,
    location: "Los Angeles",
    image: "../images/scott-webb-.jpg",
    sold: false
  },
  {
    neckline: "Halter",
    court: "Straight",
    long: "Long",
    color: "Ivory",
    size: "42",
    designer: "Marchesa",
    name: "Embroidered Tulle Gown",
    description: "An embroidered tulle gown with a halter neckline.",
    price: 6000,
    location: "New York",
    image: "../images/engin-akyurt.jpg",
    sold: false
  },
  {
    neckline: "Round",
    court: "Princess",
    long: "Long",
    color: "White",
    size: "44",
    designer: "Vera Wang",
    name: "Organza Gown",
    description: "A beautiful organza gown with a full skirt.",
    price: 7000,
    location: "Los Angeles",
    image: "../images/engin-akyurt.jpg",
    sold: false
  },
  {
    neckline: "Heart",
    court: "Siren",
    long: "Long",
    color: "Ivory",
    size: "46",
    designer: "Monique Lhuillier",
    name: "Lace Mermaid Gown",
    description: "A stunning lace mermaid gown with a sweetheart neckline.",
    price: 8000,
    location: "New York",
    image: "../images/scott-webb-.jpg",
    sold: false
  },
] 
